### ISSUE TITLE
Move this beta app to run within the *.openhatch.org domain

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-missions-oppia-beta#10]
We love it, and we should embrace it.

**Comment by paulproteus** [comment]
I have set up missions-beta.openhatch.org to be a CNAME for ghs.googlehosted.com, which I think is all that is required in openhatch.org DNS land to make this happen.

**Comment by sunu** [comment]
http://missions-beta.openhatch.org/ is up and running now :smile:
