### ISSUE TITLE
Adjust missions-beta.openhatch.org to stop redirecting to HTTP

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-missions-oppia-beta#27]
Right now, if you visit this URL:

https://missions-beta.openhatch.org/explore/10?iframed=true&locale=en&v=1#t….0&secret=DHq4Wd3DnCuMnNo48zRzuPvyLw3RyNaZayZGWzHnlDvjbXdpTGDKPAD6RPrhemsn

the browser gets redirected to a HTTP URL.

This causes problems with openhatch.org.

@sunu, can you tell the deployment that its base URL is https://missions-beta.openhatch.org not http://missions-beta.openhatch.org ?

I'm happy to help or provide other hints, if that isn't feasible.

**Comment by sunu** [comment]
Done.
