### ISSUE TITLE
Tar mission doesn't scroll down far enough, when you get to the "Creating tarballs" step

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-missions-oppia-beta#4]
I think this is actually an upstream oppia issue, but I thought I'd mention it here so that we don't forget that it hurts usability of the tar mission, too.

**Comment by sunu** [comment]
Fixed by https://github.com/sunu/oh-missions-oppia-beta/commit/47979f5dfec6a43d9e668d11a6977b1bc1516d28
