### ISSUE TITLE
The links in feedback get escaped and hence can't be clicked.

### ISSUE THREAD

**Issue by sunu** [openhatch/oh-missions-oppia-beta#6]
The links in the feedback do not get rendered as html. They get escaped and are rendered as text.

**Comment by paulproteus** [comment]
Can you clarify which links these are?

**Comment by sunu** [comment]
@paulproteus In last step of the tar mission, if you upload a tar archive with an Apple double file, a feedback message with a link to openhatch wiki shows up. But the link isn't rendered properly.

**Comment by paulproteus** [comment]
Ah hah, I see.

**Comment by sunu** [comment]
Fixed by https://github.com/sunu/oh-missions-oppia-beta/commit/91fa48e620433974a745109488cf348d6450e5ee
